

INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (1, 2018, 'Software Engineering', 'Engineering', 145);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (2, 2018, 'Civil Engineering', 'Engineering', 132);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (3, 2018, 'Mechanical Engineering', 'Engineering', 121);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (4, 2018, 'Electrical Engineering', 'Engineering', 118);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (5, 2018, 'Accounting', 'Business', 154);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (6, 2018, 'Marketing', 'Business', 138);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (7, 2018, 'Finance', 'Business', 126);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (8, 2018, 'International Business', 'Business', 119);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (9, 2018, 'History', 'Arts', 84);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (10, 2018, 'Psychology', 'Arts', 142);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (11, 2018, 'English Literature', 'Arts', 91);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (12, 2018, 'Philosophy', 'Arts', 67);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (13, 2018, 'Biology', 'Science', 133);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (14, 2018, 'Chemistry', 'Science', 102);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (15, 2018, 'Physics', 'Science', 88);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (16, 2018, 'Data Science', 'Science', 95);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (17, 2018, 'Medicine', 'Medicine', 172);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (18, 2018, 'Nursing', 'Medicine', 158);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (19, 2018, 'Pharmacy', 'Medicine', 111);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (20, 2018, 'Public Health', 'Medicine', 98);

INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (21, 2019, 'Software Engineering', 'Engineering', 152);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (22, 2019, 'Civil Engineering', 'Engineering', 129);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (23, 2019, 'Mechanical Engineering', 'Engineering', 125);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (24, 2019, 'Electrical Engineering', 'Engineering', 122);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (25, 2019, 'Accounting', 'Business', 160);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (26, 2019, 'Marketing', 'Business', 144);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (27, 2019, 'Finance', 'Business', 132);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (28, 2019, 'International Business', 'Business', 124);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (29, 2019, 'History', 'Arts', 82);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (30, 2019, 'Psychology', 'Arts', 148);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (31, 2019, 'English Literature', 'Arts', 89);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (32, 2019, 'Philosophy', 'Arts', 65);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (33, 2019, 'Biology', 'Science', 138);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (34, 2019, 'Chemistry', 'Science', 108);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (35, 2019, 'Physics', 'Science', 91);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (36, 2019, 'Data Science', 'Science', 112);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (37, 2019, 'Medicine', 'Medicine', 178);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (38, 2019, 'Nursing', 'Medicine', 162);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (39, 2019, 'Pharmacy', 'Medicine', 118);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (40, 2019, 'Public Health', 'Medicine', 104);

INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (41, 2020, 'Software Engineering', 'Engineering', 168);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (42, 2020, 'Civil Engineering', 'Engineering', 121);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (43, 2020, 'Mechanical Engineering', 'Engineering', 116);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (44, 2020, 'Electrical Engineering', 'Engineering', 114);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (45, 2020, 'Accounting', 'Business', 149);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (46, 2020, 'Marketing', 'Business', 132);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (47, 2020, 'Finance', 'Business', 124);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (48, 2020, 'International Business', 'Business', 111);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (49, 2020, 'History', 'Arts', 71);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (50, 2020, 'Psychology', 'Arts', 155);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (51, 2020, 'English Literature', 'Arts', 78);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (52, 2020, 'Philosophy', 'Arts', 58);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (53, 2020, 'Biology', 'Science', 141);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (54, 2020, 'Chemistry', 'Science', 109);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (55, 2020, 'Physics', 'Science', 86);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (56, 2020, 'Data Science', 'Science', 138);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (57, 2020, 'Medicine', 'Medicine', 190);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (58, 2020, 'Nursing', 'Medicine', 181);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (59, 2020, 'Pharmacy', 'Medicine', 124);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (60, 2020, 'Public Health', 'Medicine', 126);

INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (61, 2021, 'Software Engineering', 'Engineering', 184);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (62, 2021, 'Civil Engineering', 'Engineering', 126);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (63, 2021, 'Mechanical Engineering', 'Engineering', 119);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (64, 2021, 'Electrical Engineering', 'Engineering', 117);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (65, 2021, 'Accounting', 'Business', 153);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (66, 2021, 'Marketing', 'Business', 138);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (67, 2021, 'Finance', 'Business', 129);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (68, 2021, 'International Business', 'Business', 118);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (69, 2021, 'History', 'Arts', 74);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (70, 2021, 'Psychology', 'Arts', 162);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (71, 2021, 'English Literature', 'Arts', 82);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (72, 2021, 'Philosophy', 'Arts', 61);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (73, 2021, 'Biology', 'Science', 146);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (74, 2021, 'Chemistry', 'Science', 112);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (75, 2021, 'Physics', 'Science', 91);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (76, 2021, 'Data Science', 'Science', 162);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (77, 2021, 'Medicine', 'Medicine', 198);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (78, 2021, 'Nursing', 'Medicine', 188);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (79, 2021, 'Pharmacy', 'Medicine', 129);
INSERT INTO enrolment (id, enrolmentYear, programme, faculty, studentcount) VALUES (80, 2021, 'Public Health', 'Medicine', 134);

